# safelist
branches:
  only:
  - master

language: python
python:
  - "2.7"
# command to install dependencies
install: make install

# crear la base de datos
before_script:
  - make migrate
  - make populate

# command to run tests
script: make test
