- hosts: all
  sudo: true
  tasks:
  - name: Actualizar cache
    apt: update_cache=yes
  - name: Actualizamos repos.
    shell: sudo apt-get update && sudo apt-get upgrade -y
  - name: Instalar python-setuptools
    apt: name=python-setuptools state=present
  - name: Instalar build-essential
    apt: name=build-essential state=present
  - name: Instalar pip
    apt: name=python-pip state=present
  - name: Instalar git
    apt: name=git state=present
  - name: Ins Pyp
    apt: pkg=python-pip state=present
  - name: Instalar python-dev
    apt: pkg=python-dev state=present
  - name: Obtener aplicacion de git
    git: repo=https://github.com/edugr87/proyecto-iv.git  dest=TheWeather clone=yes force=yes
  - name: Permisos de ejecucion
    command: chmod -R +x TheWeather
  - name: Instalar requisitos
    command: sudo pip install -r TheWeather/requirements.txt
  - name: ejecutar
    command: nohup sudo python TheWeather/manage.py runserver 0.0.0.0:80
