# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='cloudiness',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_day',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_min',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_night',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind',
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=b'0'),
        ),
        migrations.AddField(
            model_name='weather',
            name='zipcode',
            field=models.CharField(default=b'lugar', max_length=30),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(default=b'description', max_length=200),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
