# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20170120_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='zipcode',
            field=models.CharField(max_length=30),
        ),
    ]
