# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_auto_20170120_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='sunrise',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.FloatField(default=b'0'),
        ),
    ]
